package com.cleanbharat.wastemanagement.repository;

import com.cleanbharat.wastemanagement.entity.RewardHistory;
import com.cleanbharat.wastemanagement.entity.User;
import com.cleanbharat.wastemanagement.entity.CleanupAssignment;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.Optional;
import java.util.List;

public interface RewardHistoryRepository extends JpaRepository<RewardHistory, Long> {
    /**
     * Returns complete reward history
     * of a cleaner.
     */
    List<RewardHistory> findByCleanerOrderByCreatedAtDesc(User cleaner);

    /**
     * Deletes reward history of a cleaner.
     */
    @Modifying
    @Transactional
    int deleteByCleaner(User cleaner);

    /**
     * Deletes reward history generated by an assignment.
     */
    @Modifying
    @Transactional
    int deleteByAssignment(CleanupAssignment assignment);

    /**
     * Returns reward history generated by an assignment.
     */
    Optional<RewardHistory> findByAssignment(CleanupAssignment assignment);

    /**
     * Tells whether an assignment has already paid out.
     *
     * One cleanup earns its reward exactly once: a municipal officer may
     * open the same completion twice, and a rework cycle ends in a second
     * approval, so the reward call must be able to recognise work it has
     * already paid for.
     */
    boolean existsByAssignment(CleanupAssignment assignment);
}
